#!/usr/bin/env python3
"""FORGE chaos_mesh — fixed-point Lorenz hop engine + rendezvous proof.

Q16 fixed-point, Euler DT=2^-7, floor-shift (fsh) => BIT-EXACT between
this model and firmware/hop.c. Python writes firmware/golden.h (the oracle).
"""
import hashlib
import hmac
import json

S = 1 << 16          # Q16 scale
SIG, RHO = 10, 28
BET_N, BET_D = 8, 3
DT_SH = 7            # DT = 2^-7
WARM, DWELL, NHOP = 3000, 50, 2000
NCH = 8
JAM = {0, 1, 2, 3}   # adversary holds half the band incl. fixed ch0
I64 = (1 << 63) - 1


def fsh(v, n):
    """Floor shift — matches C fsh() exactly (incl. negatives)."""
    return v >> n if v >= 0 else -(((-v) + (1 << n) - 1) >> n)


def step(st):
    X, Y, Z = st
    X += fsh(SIG * (Y - X), DT_SH)
    Y += fsh(fsh(X * (RHO * S - Z), 16) - Y, DT_SH)
    Z += fsh(fsh(X * Y, 16) - (BET_N * Z) // BET_D, DT_SH)
    return (X, Y, Z)


def seed_state(seed: bytes):
    u = int.from_bytes(hashlib.sha256(seed).digest()[:8], 'big')
    return (S + u % (40 * S), S + (u >> 3) % (40 * S), S + (u >> 5) % (40 * S))


def hop(Y, Z):
    wing = 0 if Y > 0 else 1
    return (wing * 4 + (fsh(abs(Z), 16) // 6) % 4) % NCH


def gen(seed: bytes, n=NHOP, warm=WARM):
    st = seed_state(seed)
    for _ in range(warm):
        st = step(st)
    out, peak = [], 0
    for _ in range(n):
        for _ in range(DWELL):
            st = step(st)
        peak = max(peak, abs(st[0]), abs(st[1]), abs(st[2]))
        out.append(hop(st[1], st[2]))
    return out, peak


tests = {}

# ---- T1: determinism + int64 safety + golden oracle ----
h1, peak = gen(b'FORGE-mesh-seed-01')
h2, _ = gen(b'FORGE-mesh-seed-01')
det = sum(a == b for a, b in zip(h1, h2))
tests['T1_engine'] = {'identical': det, 'peak_state': peak,
                      'pass': det == NHOP and peak < I64}
gh = ['/* AUTO-GENERATED by chaos_mesh.py — oracle for test_host. DO NOT EDIT. */',
      '#pragma once', '#include <stdint.h>', '#define NHOP 2000',
      'static const uint8_t GOLDEN[NHOP] = {']
for i in range(0, NHOP, 20):
    gh.append(' ' + ','.join(str(v) for v in h1[i:i + 20]) + ',')
gh.append('};')
open('firmware/golden.h', 'w').write('\n'.join(gh) + '\n')

# ---- T2: rendezvous under clock drift (window +-2 slots) ----
SLOT, DRIFT = 60.0, 500e-6
found = 0
for i in range(NHOP):
    actual = i + int((i * SLOT * DRIFT) // SLOT)  # node slot vs gateway slot
    if abs(actual - i) <= 2 and 0 <= actual < NHOP:
        found += 1  # gateway opens predicted +-2 => actual inside
tests['T2_rendezvous'] = {'found': found, 'pass': found == NHOP}

# ---- T3: jam evasion ----
succ_h = sum(x not in JAM for x in h1) / NHOP
tests['T3_jam'] = {'hopper': round(succ_h, 4), 'fixed': 0.0,
                   'pass': succ_h >= 0.35}

# ---- T4: seed avalanche + HMAC auth ----
hf, _ = gen(b'FORGE-mesh-seed-02')  # 1-bit-ish different seed
differ = sum(a != b for a, b in zip(h1, hf)) / NHOP
KEY, MSG = b'pair-key-16bytes!', b'node7:T=31.2,H=18'
tag = hmac.new(KEY, MSG, hashlib.sha256).digest()
ok_valid = hmac.compare_digest(tag, hmac.new(KEY, MSG, hashlib.sha256).digest())
ok_forge = hmac.compare_digest(tag, hmac.new(KEY, b'node7:T=99.9,H=18', hashlib.sha256).digest())
ok_wrongk = hmac.compare_digest(tag, hmac.new(b'wrong-key-16byte!', MSG, hashlib.sha256).digest())
tests['T4_security'] = {'avalanche': round(differ, 4), 'valid_accept': ok_valid,
                        'forged_reject': not ok_forge, 'wrongkey_reject': not ok_wrongk,
                        'pass': differ >= 0.40 and ok_valid and not ok_forge and not ok_wrongk}

# ---- T5: energy vs TEG budget ----
V = 3.3
e_day = 1440 * (0.030 * 0.025 * V + 0.012 * 0.008 * V + 5e-6 * 60 * V)
budget = 0.0025 * 86400
tests['T5_energy'] = {'J_per_day': round(e_day, 2),
                      'pct_budget': round(100 * e_day / budget, 2),
                      'pass': e_day < 0.05 * budget}

# ---- waterfall chart ----
NSHOW = 200
CW, RH, LM = 3, 22, 30
W, H = LM + NSHOW * CW + 10, NCH * RH + 30
el = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
      f'font-family="Tahoma" font-size="11">',
      f'<rect width="{W}" height="{H}" fill="#0b1220"/>']
for ch in range(NCH):
    y = ch * RH + 10
    if ch in JAM:
        el.append(f'<rect x="{LM}" y="{y}" width="{NSHOW*CW}" height="{RH-2}" fill="#7f1d1d"/>')
    el.append(f'<text x="4" y="{y+15}" fill="#e2e8f0">ch{ch}</text>')
for i in range(NSHOW):
    x = LM + i * CW
    el.append(f'<rect x="{x}" y="{h1[i]*RH+12}" width="2" height="{RH-6}" fill="#4ade80"/>')
    el.append(f'<rect x="{x}" y="12" width="2" height="4" fill="#f87171"/>')
el.append(f'<text x="{LM}" y="{H-6}" fill="#94a3b8">أخضر=القافزة تنجو | أحمر=الثابتة على ch0 تختنق | الخلفية الحمراء=نصف النطاق مشوش</text>')
el.append('</svg>')
open('waterfall.svg', 'w', encoding='utf-8').write('\n'.join(el))

ok = all(t['pass'] for t in tests.values())
json.dump({'tests': tests, 'verdict': 'MESH PROOF [VERIFIED]' if ok else 'FAIL'},
          open('results.json', 'w'), indent=1)
for k, t in tests.items():
    print(('PASS' if t['pass'] else 'FAIL'), k, {a: b for a, b in t.items() if a != 'pass'})
print('VERDICT:', 'MESH PROOF [VERIFIED]' if ok else 'FAIL')
raise SystemExit(0 if ok else 1)
